# vim:fileencoding=utf-8:ft=kitty

#: Fonts ----------------------------------------------------------

font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

#: Cursor ---------------------------------------------------------

cursor_shape block
cursor_blink_interval 0

#: Scrollback -----------------------------------------------------

scrollback_lines 10000

#: Mouse ----------------------------------------------------------

mouse_hide_wait 0
url_style curly

#: Performance ------------------------------------------------------

repaint_delay 8
input_delay 3
sync_to_monitor yes

#: Bell -------------------------------------------------------------

enable_audio_bell no
window_alert_on_bell yes

#: Window layout ------------------------------------------------------

remember_window_size  no
initial_window_width  1280
initial_window_height 800
window_padding_width 4
confirm_os_window_close 0

#: Shell ------------------------------------------------------------

shell /bin/zsh
shell_integration enabled

#: macOS -------------------------------------------------------------

macos_option_as_alt both
macos_quit_when_last_window_closed no

#: Misc -------------------------------------------------------------

allow_remote_control yes
update_check_interval 0

#: Color scheme -------------------------------------------------------

include catppuccin-frappe.conf

#: Keyboard shortcuts --------------------------------------------------

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
